Parameters:
  DistributionId:
    Type: String
  SNSTopicArn:
    Type: String
    Description: SNS topic ARN for alarm notifications
  ThroughputThresholdBytes:
    Type: Number
    Description: "The threshold (bytes/min) of the alarm. Default: 150GB/min (~20Gbps, 50% of default quota)"
    Default: 150000000000
  RequestsPerMinuteThreshold:
    Type: Number
    Description: "The threshold (requests/min) of the alarm. Default: 4,200,000, 70% of default quota"
    Default: 4200000

Resources:
  RequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm on high requests per second
      ActionsEnabled: True
      AlarmActions: 
          - !Ref SNSTopicArn
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Threshold: !Ref RequestsPerMinuteThreshold
      Metrics:
        - Id: rps
          Label: RequestsPerSecond
          MetricStat:
            Metric:
              Namespace: AWS/CloudFront
              MetricName: Requests
              Dimensions:
                - Name: Region
                  Value: Global
                - Name: DistributionId
                  Value: !Ref DistributionId
            Period: 60
            Stat: Sum
            Unit: Count

  ThroughputAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmDescription: Alarm on high CloudFront bandwidth for the specified distribution
      ActionsEnabled: True
      AlarmActions: 
        - !Ref SNSTopicArn
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Threshold: !Ref ThroughputThresholdBytes
      Metrics: 
        - Id: rx
          Label: BytesUploaded
          ReturnData: False
          MetricStat:
            Metric:
              Namespace: AWS/CloudFront
              MetricName: BytesUploaded
              Dimensions:
                - Name: Region
                  Value: Global
                - Name: DistributionId
                  Value: !Ref DistributionId
            Period: 60
            Stat: Sum
            Unit: Bytes

        - Id: tx
          Label: BytesDownloaded
          ReturnData: False
          MetricStat:
            Metric:
              Namespace: AWS/CloudFront
              MetricName: BytesDownloaded
              Dimensions:
                - Name: Region
                  Value: Global
                - Name: DistributionId
                  Value: !Ref DistributionId
            Period: 60
            Stat: Sum
            Unit: Bytes

        - Id: totalBytes
          Label: TotalBytes
          Expression: "tx + rx"